# Generated by Django 2.2.3 on 2019-07-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20190722_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admin',
        ),
    ]
