# Generated by Django 2.2.3 on 2019-07-25 03:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0007_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='group_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
